// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/0xfzz/tuwitt/ent/thread"
)

// Thread is the model entity for the Thread schema.
type Thread struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// IsCommentDisabled holds the value of the "is_comment_disabled" field.
	IsCommentDisabled bool `json:"is_comment_disabled,omitempty"`
	// Visibility holds the value of the "visibility" field.
	Visibility thread.Visibility `json:"visibility,omitempty"`
	// Status holds the value of the "status" field.
	Status thread.Status `json:"status,omitempty"`
	// IsDeleted holds the value of the "is_deleted" field.
	IsDeleted bool `json:"is_deleted,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ThreadQuery when eager-loading is set.
	Edges                ThreadEdges `json:"edges"`
	thread_child_threads *int
	selectValues         sql.SelectValues
}

// ThreadEdges holds the relations/edges for other nodes in the graph.
type ThreadEdges struct {
	// ParentThread holds the value of the parent_thread edge.
	ParentThread *Thread `json:"parent_thread,omitempty"`
	// ChildThreads holds the value of the child_threads edge.
	ChildThreads []*Thread `json:"child_threads,omitempty"`
	// Images holds the value of the images edge.
	Images []*Media `json:"images,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ParentThreadOrErr returns the ParentThread value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ThreadEdges) ParentThreadOrErr() (*Thread, error) {
	if e.loadedTypes[0] {
		if e.ParentThread == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: thread.Label}
		}
		return e.ParentThread, nil
	}
	return nil, &NotLoadedError{edge: "parent_thread"}
}

// ChildThreadsOrErr returns the ChildThreads value or an error if the edge
// was not loaded in eager-loading.
func (e ThreadEdges) ChildThreadsOrErr() ([]*Thread, error) {
	if e.loadedTypes[1] {
		return e.ChildThreads, nil
	}
	return nil, &NotLoadedError{edge: "child_threads"}
}

// ImagesOrErr returns the Images value or an error if the edge
// was not loaded in eager-loading.
func (e ThreadEdges) ImagesOrErr() ([]*Media, error) {
	if e.loadedTypes[2] {
		return e.Images, nil
	}
	return nil, &NotLoadedError{edge: "images"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Thread) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case thread.FieldIsCommentDisabled, thread.FieldIsDeleted:
			values[i] = new(sql.NullBool)
		case thread.FieldID:
			values[i] = new(sql.NullInt64)
		case thread.FieldContent, thread.FieldVisibility, thread.FieldStatus:
			values[i] = new(sql.NullString)
		case thread.ForeignKeys[0]: // thread_child_threads
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Thread fields.
func (t *Thread) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case thread.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			t.ID = int(value.Int64)
		case thread.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				t.Content = value.String
			}
		case thread.FieldIsCommentDisabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_comment_disabled", values[i])
			} else if value.Valid {
				t.IsCommentDisabled = value.Bool
			}
		case thread.FieldVisibility:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field visibility", values[i])
			} else if value.Valid {
				t.Visibility = thread.Visibility(value.String)
			}
		case thread.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				t.Status = thread.Status(value.String)
			}
		case thread.FieldIsDeleted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_deleted", values[i])
			} else if value.Valid {
				t.IsDeleted = value.Bool
			}
		case thread.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field thread_child_threads", value)
			} else if value.Valid {
				t.thread_child_threads = new(int)
				*t.thread_child_threads = int(value.Int64)
			}
		default:
			t.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Thread.
// This includes values selected through modifiers, order, etc.
func (t *Thread) Value(name string) (ent.Value, error) {
	return t.selectValues.Get(name)
}

// QueryParentThread queries the "parent_thread" edge of the Thread entity.
func (t *Thread) QueryParentThread() *ThreadQuery {
	return NewThreadClient(t.config).QueryParentThread(t)
}

// QueryChildThreads queries the "child_threads" edge of the Thread entity.
func (t *Thread) QueryChildThreads() *ThreadQuery {
	return NewThreadClient(t.config).QueryChildThreads(t)
}

// QueryImages queries the "images" edge of the Thread entity.
func (t *Thread) QueryImages() *MediaQuery {
	return NewThreadClient(t.config).QueryImages(t)
}

// Update returns a builder for updating this Thread.
// Note that you need to call Thread.Unwrap() before calling this method if this Thread
// was returned from a transaction, and the transaction was committed or rolled back.
func (t *Thread) Update() *ThreadUpdateOne {
	return NewThreadClient(t.config).UpdateOne(t)
}

// Unwrap unwraps the Thread entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (t *Thread) Unwrap() *Thread {
	_tx, ok := t.config.driver.(*txDriver)
	if !ok {
		panic("ent: Thread is not a transactional entity")
	}
	t.config.driver = _tx.drv
	return t
}

// String implements the fmt.Stringer.
func (t *Thread) String() string {
	var builder strings.Builder
	builder.WriteString("Thread(")
	builder.WriteString(fmt.Sprintf("id=%v, ", t.ID))
	builder.WriteString("content=")
	builder.WriteString(t.Content)
	builder.WriteString(", ")
	builder.WriteString("is_comment_disabled=")
	builder.WriteString(fmt.Sprintf("%v", t.IsCommentDisabled))
	builder.WriteString(", ")
	builder.WriteString("visibility=")
	builder.WriteString(fmt.Sprintf("%v", t.Visibility))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", t.Status))
	builder.WriteString(", ")
	builder.WriteString("is_deleted=")
	builder.WriteString(fmt.Sprintf("%v", t.IsDeleted))
	builder.WriteByte(')')
	return builder.String()
}

// Threads is a parsable slice of Thread.
type Threads []*Thread
