// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/0xfzz/tuwitt/ent/media"
	"github.com/0xfzz/tuwitt/ent/predicate"
	"github.com/0xfzz/tuwitt/ent/thread"
	"github.com/0xfzz/tuwitt/ent/threadcount"
	"github.com/0xfzz/tuwitt/ent/useraccount"
)

// ThreadUpdate is the builder for updating Thread entities.
type ThreadUpdate struct {
	config
	hooks    []Hook
	mutation *ThreadMutation
}

// Where appends a list predicates to the ThreadUpdate builder.
func (tu *ThreadUpdate) Where(ps ...predicate.Thread) *ThreadUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *ThreadUpdate) SetUpdatedAt(t time.Time) *ThreadUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetContent sets the "content" field.
func (tu *ThreadUpdate) SetContent(s string) *ThreadUpdate {
	tu.mutation.SetContent(s)
	return tu
}

// SetIsCommentDisabled sets the "is_comment_disabled" field.
func (tu *ThreadUpdate) SetIsCommentDisabled(b bool) *ThreadUpdate {
	tu.mutation.SetIsCommentDisabled(b)
	return tu
}

// SetNillableIsCommentDisabled sets the "is_comment_disabled" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableIsCommentDisabled(b *bool) *ThreadUpdate {
	if b != nil {
		tu.SetIsCommentDisabled(*b)
	}
	return tu
}

// SetVisibility sets the "visibility" field.
func (tu *ThreadUpdate) SetVisibility(t thread.Visibility) *ThreadUpdate {
	tu.mutation.SetVisibility(t)
	return tu
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableVisibility(t *thread.Visibility) *ThreadUpdate {
	if t != nil {
		tu.SetVisibility(*t)
	}
	return tu
}

// SetStatus sets the "status" field.
func (tu *ThreadUpdate) SetStatus(t thread.Status) *ThreadUpdate {
	tu.mutation.SetStatus(t)
	return tu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableStatus(t *thread.Status) *ThreadUpdate {
	if t != nil {
		tu.SetStatus(*t)
	}
	return tu
}

// SetIsDeleted sets the "is_deleted" field.
func (tu *ThreadUpdate) SetIsDeleted(b bool) *ThreadUpdate {
	tu.mutation.SetIsDeleted(b)
	return tu
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableIsDeleted(b *bool) *ThreadUpdate {
	if b != nil {
		tu.SetIsDeleted(*b)
	}
	return tu
}

// SetAuthorID sets the "author_id" field.
func (tu *ThreadUpdate) SetAuthorID(i int) *ThreadUpdate {
	tu.mutation.SetAuthorID(i)
	return tu
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableAuthorID(i *int) *ThreadUpdate {
	if i != nil {
		tu.SetAuthorID(*i)
	}
	return tu
}

// ClearAuthorID clears the value of the "author_id" field.
func (tu *ThreadUpdate) ClearAuthorID() *ThreadUpdate {
	tu.mutation.ClearAuthorID()
	return tu
}

// SetParentID sets the "parent_id" field.
func (tu *ThreadUpdate) SetParentID(i int) *ThreadUpdate {
	tu.mutation.SetParentID(i)
	return tu
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableParentID(i *int) *ThreadUpdate {
	if i != nil {
		tu.SetParentID(*i)
	}
	return tu
}

// ClearParentID clears the value of the "parent_id" field.
func (tu *ThreadUpdate) ClearParentID() *ThreadUpdate {
	tu.mutation.ClearParentID()
	return tu
}

// SetRepostThreadID sets the "repost_thread_id" field.
func (tu *ThreadUpdate) SetRepostThreadID(i int) *ThreadUpdate {
	tu.mutation.SetRepostThreadID(i)
	return tu
}

// SetNillableRepostThreadID sets the "repost_thread_id" field if the given value is not nil.
func (tu *ThreadUpdate) SetNillableRepostThreadID(i *int) *ThreadUpdate {
	if i != nil {
		tu.SetRepostThreadID(*i)
	}
	return tu
}

// ClearRepostThreadID clears the value of the "repost_thread_id" field.
func (tu *ThreadUpdate) ClearRepostThreadID() *ThreadUpdate {
	tu.mutation.ClearRepostThreadID()
	return tu
}

// SetAuthor sets the "author" edge to the UserAccount entity.
func (tu *ThreadUpdate) SetAuthor(u *UserAccount) *ThreadUpdate {
	return tu.SetAuthorID(u.ID)
}

// SetParent sets the "parent" edge to the Thread entity.
func (tu *ThreadUpdate) SetParent(t *Thread) *ThreadUpdate {
	return tu.SetParentID(t.ID)
}

// AddChildIDs adds the "children" edge to the Thread entity by IDs.
func (tu *ThreadUpdate) AddChildIDs(ids ...int) *ThreadUpdate {
	tu.mutation.AddChildIDs(ids...)
	return tu
}

// AddChildren adds the "children" edges to the Thread entity.
func (tu *ThreadUpdate) AddChildren(t ...*Thread) *ThreadUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddChildIDs(ids...)
}

// AddThreadCountIDs adds the "thread_count" edge to the ThreadCount entity by IDs.
func (tu *ThreadUpdate) AddThreadCountIDs(ids ...int) *ThreadUpdate {
	tu.mutation.AddThreadCountIDs(ids...)
	return tu
}

// AddThreadCount adds the "thread_count" edges to the ThreadCount entity.
func (tu *ThreadUpdate) AddThreadCount(t ...*ThreadCount) *ThreadUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.AddThreadCountIDs(ids...)
}

// SetRepostedID sets the "reposted" edge to the Thread entity by ID.
func (tu *ThreadUpdate) SetRepostedID(id int) *ThreadUpdate {
	tu.mutation.SetRepostedID(id)
	return tu
}

// SetNillableRepostedID sets the "reposted" edge to the Thread entity by ID if the given value is not nil.
func (tu *ThreadUpdate) SetNillableRepostedID(id *int) *ThreadUpdate {
	if id != nil {
		tu = tu.SetRepostedID(*id)
	}
	return tu
}

// SetReposted sets the "reposted" edge to the Thread entity.
func (tu *ThreadUpdate) SetReposted(t *Thread) *ThreadUpdate {
	return tu.SetRepostedID(t.ID)
}

// SetRepostID sets the "repost" edge to the Thread entity by ID.
func (tu *ThreadUpdate) SetRepostID(id int) *ThreadUpdate {
	tu.mutation.SetRepostID(id)
	return tu
}

// SetNillableRepostID sets the "repost" edge to the Thread entity by ID if the given value is not nil.
func (tu *ThreadUpdate) SetNillableRepostID(id *int) *ThreadUpdate {
	if id != nil {
		tu = tu.SetRepostID(*id)
	}
	return tu
}

// SetRepost sets the "repost" edge to the Thread entity.
func (tu *ThreadUpdate) SetRepost(t *Thread) *ThreadUpdate {
	return tu.SetRepostID(t.ID)
}

// AddImageIDs adds the "images" edge to the Media entity by IDs.
func (tu *ThreadUpdate) AddImageIDs(ids ...int) *ThreadUpdate {
	tu.mutation.AddImageIDs(ids...)
	return tu
}

// AddImages adds the "images" edges to the Media entity.
func (tu *ThreadUpdate) AddImages(m ...*Media) *ThreadUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.AddImageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (tu *ThreadUpdate) Mutation() *ThreadMutation {
	return tu.mutation
}

// ClearAuthor clears the "author" edge to the UserAccount entity.
func (tu *ThreadUpdate) ClearAuthor() *ThreadUpdate {
	tu.mutation.ClearAuthor()
	return tu
}

// ClearParent clears the "parent" edge to the Thread entity.
func (tu *ThreadUpdate) ClearParent() *ThreadUpdate {
	tu.mutation.ClearParent()
	return tu
}

// ClearChildren clears all "children" edges to the Thread entity.
func (tu *ThreadUpdate) ClearChildren() *ThreadUpdate {
	tu.mutation.ClearChildren()
	return tu
}

// RemoveChildIDs removes the "children" edge to Thread entities by IDs.
func (tu *ThreadUpdate) RemoveChildIDs(ids ...int) *ThreadUpdate {
	tu.mutation.RemoveChildIDs(ids...)
	return tu
}

// RemoveChildren removes "children" edges to Thread entities.
func (tu *ThreadUpdate) RemoveChildren(t ...*Thread) *ThreadUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveChildIDs(ids...)
}

// ClearThreadCount clears all "thread_count" edges to the ThreadCount entity.
func (tu *ThreadUpdate) ClearThreadCount() *ThreadUpdate {
	tu.mutation.ClearThreadCount()
	return tu
}

// RemoveThreadCountIDs removes the "thread_count" edge to ThreadCount entities by IDs.
func (tu *ThreadUpdate) RemoveThreadCountIDs(ids ...int) *ThreadUpdate {
	tu.mutation.RemoveThreadCountIDs(ids...)
	return tu
}

// RemoveThreadCount removes "thread_count" edges to ThreadCount entities.
func (tu *ThreadUpdate) RemoveThreadCount(t ...*ThreadCount) *ThreadUpdate {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tu.RemoveThreadCountIDs(ids...)
}

// ClearReposted clears the "reposted" edge to the Thread entity.
func (tu *ThreadUpdate) ClearReposted() *ThreadUpdate {
	tu.mutation.ClearReposted()
	return tu
}

// ClearRepost clears the "repost" edge to the Thread entity.
func (tu *ThreadUpdate) ClearRepost() *ThreadUpdate {
	tu.mutation.ClearRepost()
	return tu
}

// ClearImages clears all "images" edges to the Media entity.
func (tu *ThreadUpdate) ClearImages() *ThreadUpdate {
	tu.mutation.ClearImages()
	return tu
}

// RemoveImageIDs removes the "images" edge to Media entities by IDs.
func (tu *ThreadUpdate) RemoveImageIDs(ids ...int) *ThreadUpdate {
	tu.mutation.RemoveImageIDs(ids...)
	return tu
}

// RemoveImages removes "images" edges to Media entities.
func (tu *ThreadUpdate) RemoveImages(m ...*Media) *ThreadUpdate {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tu.RemoveImageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *ThreadUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *ThreadUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *ThreadUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *ThreadUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *ThreadUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := thread.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tu *ThreadUpdate) check() error {
	if v, ok := tu.mutation.Visibility(); ok {
		if err := thread.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Thread.visibility": %w`, err)}
		}
	}
	if v, ok := tu.mutation.Status(); ok {
		if err := thread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Thread.status": %w`, err)}
		}
	}
	return nil
}

func (tu *ThreadUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := tu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(thread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Content(); ok {
		_spec.SetField(thread.FieldContent, field.TypeString, value)
	}
	if value, ok := tu.mutation.IsCommentDisabled(); ok {
		_spec.SetField(thread.FieldIsCommentDisabled, field.TypeBool, value)
	}
	if value, ok := tu.mutation.Visibility(); ok {
		_spec.SetField(thread.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.Status(); ok {
		_spec.SetField(thread.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tu.mutation.IsDeleted(); ok {
		_spec.SetField(thread.FieldIsDeleted, field.TypeBool, value)
	}
	if tu.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AuthorTable,
			Columns: []string{thread.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AuthorTable,
			Columns: []string{thread.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.ParentTable,
			Columns: []string{thread.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.ParentTable,
			Columns: []string{thread.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !tu.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ThreadCountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedThreadCountIDs(); len(nodes) > 0 && !tu.mutation.ThreadCountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ThreadCountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.RepostedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   thread.RepostedTable,
			Columns: []string{thread.RepostedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RepostedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   thread.RepostedTable,
			Columns: []string{thread.RepostedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.RepostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   thread.RepostTable,
			Columns: []string{thread.RepostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RepostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   thread.RepostTable,
			Columns: []string{thread.RepostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tu.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.RemovedImagesIDs(); len(nodes) > 0 && !tu.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// ThreadUpdateOne is the builder for updating a single Thread entity.
type ThreadUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ThreadMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *ThreadUpdateOne) SetUpdatedAt(t time.Time) *ThreadUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetContent sets the "content" field.
func (tuo *ThreadUpdateOne) SetContent(s string) *ThreadUpdateOne {
	tuo.mutation.SetContent(s)
	return tuo
}

// SetIsCommentDisabled sets the "is_comment_disabled" field.
func (tuo *ThreadUpdateOne) SetIsCommentDisabled(b bool) *ThreadUpdateOne {
	tuo.mutation.SetIsCommentDisabled(b)
	return tuo
}

// SetNillableIsCommentDisabled sets the "is_comment_disabled" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableIsCommentDisabled(b *bool) *ThreadUpdateOne {
	if b != nil {
		tuo.SetIsCommentDisabled(*b)
	}
	return tuo
}

// SetVisibility sets the "visibility" field.
func (tuo *ThreadUpdateOne) SetVisibility(t thread.Visibility) *ThreadUpdateOne {
	tuo.mutation.SetVisibility(t)
	return tuo
}

// SetNillableVisibility sets the "visibility" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableVisibility(t *thread.Visibility) *ThreadUpdateOne {
	if t != nil {
		tuo.SetVisibility(*t)
	}
	return tuo
}

// SetStatus sets the "status" field.
func (tuo *ThreadUpdateOne) SetStatus(t thread.Status) *ThreadUpdateOne {
	tuo.mutation.SetStatus(t)
	return tuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableStatus(t *thread.Status) *ThreadUpdateOne {
	if t != nil {
		tuo.SetStatus(*t)
	}
	return tuo
}

// SetIsDeleted sets the "is_deleted" field.
func (tuo *ThreadUpdateOne) SetIsDeleted(b bool) *ThreadUpdateOne {
	tuo.mutation.SetIsDeleted(b)
	return tuo
}

// SetNillableIsDeleted sets the "is_deleted" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableIsDeleted(b *bool) *ThreadUpdateOne {
	if b != nil {
		tuo.SetIsDeleted(*b)
	}
	return tuo
}

// SetAuthorID sets the "author_id" field.
func (tuo *ThreadUpdateOne) SetAuthorID(i int) *ThreadUpdateOne {
	tuo.mutation.SetAuthorID(i)
	return tuo
}

// SetNillableAuthorID sets the "author_id" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableAuthorID(i *int) *ThreadUpdateOne {
	if i != nil {
		tuo.SetAuthorID(*i)
	}
	return tuo
}

// ClearAuthorID clears the value of the "author_id" field.
func (tuo *ThreadUpdateOne) ClearAuthorID() *ThreadUpdateOne {
	tuo.mutation.ClearAuthorID()
	return tuo
}

// SetParentID sets the "parent_id" field.
func (tuo *ThreadUpdateOne) SetParentID(i int) *ThreadUpdateOne {
	tuo.mutation.SetParentID(i)
	return tuo
}

// SetNillableParentID sets the "parent_id" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableParentID(i *int) *ThreadUpdateOne {
	if i != nil {
		tuo.SetParentID(*i)
	}
	return tuo
}

// ClearParentID clears the value of the "parent_id" field.
func (tuo *ThreadUpdateOne) ClearParentID() *ThreadUpdateOne {
	tuo.mutation.ClearParentID()
	return tuo
}

// SetRepostThreadID sets the "repost_thread_id" field.
func (tuo *ThreadUpdateOne) SetRepostThreadID(i int) *ThreadUpdateOne {
	tuo.mutation.SetRepostThreadID(i)
	return tuo
}

// SetNillableRepostThreadID sets the "repost_thread_id" field if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableRepostThreadID(i *int) *ThreadUpdateOne {
	if i != nil {
		tuo.SetRepostThreadID(*i)
	}
	return tuo
}

// ClearRepostThreadID clears the value of the "repost_thread_id" field.
func (tuo *ThreadUpdateOne) ClearRepostThreadID() *ThreadUpdateOne {
	tuo.mutation.ClearRepostThreadID()
	return tuo
}

// SetAuthor sets the "author" edge to the UserAccount entity.
func (tuo *ThreadUpdateOne) SetAuthor(u *UserAccount) *ThreadUpdateOne {
	return tuo.SetAuthorID(u.ID)
}

// SetParent sets the "parent" edge to the Thread entity.
func (tuo *ThreadUpdateOne) SetParent(t *Thread) *ThreadUpdateOne {
	return tuo.SetParentID(t.ID)
}

// AddChildIDs adds the "children" edge to the Thread entity by IDs.
func (tuo *ThreadUpdateOne) AddChildIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.AddChildIDs(ids...)
	return tuo
}

// AddChildren adds the "children" edges to the Thread entity.
func (tuo *ThreadUpdateOne) AddChildren(t ...*Thread) *ThreadUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddChildIDs(ids...)
}

// AddThreadCountIDs adds the "thread_count" edge to the ThreadCount entity by IDs.
func (tuo *ThreadUpdateOne) AddThreadCountIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.AddThreadCountIDs(ids...)
	return tuo
}

// AddThreadCount adds the "thread_count" edges to the ThreadCount entity.
func (tuo *ThreadUpdateOne) AddThreadCount(t ...*ThreadCount) *ThreadUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.AddThreadCountIDs(ids...)
}

// SetRepostedID sets the "reposted" edge to the Thread entity by ID.
func (tuo *ThreadUpdateOne) SetRepostedID(id int) *ThreadUpdateOne {
	tuo.mutation.SetRepostedID(id)
	return tuo
}

// SetNillableRepostedID sets the "reposted" edge to the Thread entity by ID if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableRepostedID(id *int) *ThreadUpdateOne {
	if id != nil {
		tuo = tuo.SetRepostedID(*id)
	}
	return tuo
}

// SetReposted sets the "reposted" edge to the Thread entity.
func (tuo *ThreadUpdateOne) SetReposted(t *Thread) *ThreadUpdateOne {
	return tuo.SetRepostedID(t.ID)
}

// SetRepostID sets the "repost" edge to the Thread entity by ID.
func (tuo *ThreadUpdateOne) SetRepostID(id int) *ThreadUpdateOne {
	tuo.mutation.SetRepostID(id)
	return tuo
}

// SetNillableRepostID sets the "repost" edge to the Thread entity by ID if the given value is not nil.
func (tuo *ThreadUpdateOne) SetNillableRepostID(id *int) *ThreadUpdateOne {
	if id != nil {
		tuo = tuo.SetRepostID(*id)
	}
	return tuo
}

// SetRepost sets the "repost" edge to the Thread entity.
func (tuo *ThreadUpdateOne) SetRepost(t *Thread) *ThreadUpdateOne {
	return tuo.SetRepostID(t.ID)
}

// AddImageIDs adds the "images" edge to the Media entity by IDs.
func (tuo *ThreadUpdateOne) AddImageIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.AddImageIDs(ids...)
	return tuo
}

// AddImages adds the "images" edges to the Media entity.
func (tuo *ThreadUpdateOne) AddImages(m ...*Media) *ThreadUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.AddImageIDs(ids...)
}

// Mutation returns the ThreadMutation object of the builder.
func (tuo *ThreadUpdateOne) Mutation() *ThreadMutation {
	return tuo.mutation
}

// ClearAuthor clears the "author" edge to the UserAccount entity.
func (tuo *ThreadUpdateOne) ClearAuthor() *ThreadUpdateOne {
	tuo.mutation.ClearAuthor()
	return tuo
}

// ClearParent clears the "parent" edge to the Thread entity.
func (tuo *ThreadUpdateOne) ClearParent() *ThreadUpdateOne {
	tuo.mutation.ClearParent()
	return tuo
}

// ClearChildren clears all "children" edges to the Thread entity.
func (tuo *ThreadUpdateOne) ClearChildren() *ThreadUpdateOne {
	tuo.mutation.ClearChildren()
	return tuo
}

// RemoveChildIDs removes the "children" edge to Thread entities by IDs.
func (tuo *ThreadUpdateOne) RemoveChildIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.RemoveChildIDs(ids...)
	return tuo
}

// RemoveChildren removes "children" edges to Thread entities.
func (tuo *ThreadUpdateOne) RemoveChildren(t ...*Thread) *ThreadUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveChildIDs(ids...)
}

// ClearThreadCount clears all "thread_count" edges to the ThreadCount entity.
func (tuo *ThreadUpdateOne) ClearThreadCount() *ThreadUpdateOne {
	tuo.mutation.ClearThreadCount()
	return tuo
}

// RemoveThreadCountIDs removes the "thread_count" edge to ThreadCount entities by IDs.
func (tuo *ThreadUpdateOne) RemoveThreadCountIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.RemoveThreadCountIDs(ids...)
	return tuo
}

// RemoveThreadCount removes "thread_count" edges to ThreadCount entities.
func (tuo *ThreadUpdateOne) RemoveThreadCount(t ...*ThreadCount) *ThreadUpdateOne {
	ids := make([]int, len(t))
	for i := range t {
		ids[i] = t[i].ID
	}
	return tuo.RemoveThreadCountIDs(ids...)
}

// ClearReposted clears the "reposted" edge to the Thread entity.
func (tuo *ThreadUpdateOne) ClearReposted() *ThreadUpdateOne {
	tuo.mutation.ClearReposted()
	return tuo
}

// ClearRepost clears the "repost" edge to the Thread entity.
func (tuo *ThreadUpdateOne) ClearRepost() *ThreadUpdateOne {
	tuo.mutation.ClearRepost()
	return tuo
}

// ClearImages clears all "images" edges to the Media entity.
func (tuo *ThreadUpdateOne) ClearImages() *ThreadUpdateOne {
	tuo.mutation.ClearImages()
	return tuo
}

// RemoveImageIDs removes the "images" edge to Media entities by IDs.
func (tuo *ThreadUpdateOne) RemoveImageIDs(ids ...int) *ThreadUpdateOne {
	tuo.mutation.RemoveImageIDs(ids...)
	return tuo
}

// RemoveImages removes "images" edges to Media entities.
func (tuo *ThreadUpdateOne) RemoveImages(m ...*Media) *ThreadUpdateOne {
	ids := make([]int, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return tuo.RemoveImageIDs(ids...)
}

// Where appends a list predicates to the ThreadUpdate builder.
func (tuo *ThreadUpdateOne) Where(ps ...predicate.Thread) *ThreadUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *ThreadUpdateOne) Select(field string, fields ...string) *ThreadUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Thread entity.
func (tuo *ThreadUpdateOne) Save(ctx context.Context) (*Thread, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *ThreadUpdateOne) SaveX(ctx context.Context) *Thread {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *ThreadUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *ThreadUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *ThreadUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := thread.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (tuo *ThreadUpdateOne) check() error {
	if v, ok := tuo.mutation.Visibility(); ok {
		if err := thread.VisibilityValidator(v); err != nil {
			return &ValidationError{Name: "visibility", err: fmt.Errorf(`ent: validator failed for field "Thread.visibility": %w`, err)}
		}
	}
	if v, ok := tuo.mutation.Status(); ok {
		if err := thread.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Thread.status": %w`, err)}
		}
	}
	return nil
}

func (tuo *ThreadUpdateOne) sqlSave(ctx context.Context) (_node *Thread, err error) {
	if err := tuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(thread.Table, thread.Columns, sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Thread.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, thread.FieldID)
		for _, f := range fields {
			if !thread.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != thread.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(thread.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Content(); ok {
		_spec.SetField(thread.FieldContent, field.TypeString, value)
	}
	if value, ok := tuo.mutation.IsCommentDisabled(); ok {
		_spec.SetField(thread.FieldIsCommentDisabled, field.TypeBool, value)
	}
	if value, ok := tuo.mutation.Visibility(); ok {
		_spec.SetField(thread.FieldVisibility, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.Status(); ok {
		_spec.SetField(thread.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := tuo.mutation.IsDeleted(); ok {
		_spec.SetField(thread.FieldIsDeleted, field.TypeBool, value)
	}
	if tuo.mutation.AuthorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AuthorTable,
			Columns: []string{thread.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.AuthorTable,
			Columns: []string{thread.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(useraccount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ParentCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.ParentTable,
			Columns: []string{thread.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ParentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   thread.ParentTable,
			Columns: []string{thread.ParentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedChildrenIDs(); len(nodes) > 0 && !tuo.mutation.ChildrenCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ChildrenIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ChildrenTable,
			Columns: []string{thread.ChildrenColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ThreadCountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedThreadCountIDs(); len(nodes) > 0 && !tuo.mutation.ThreadCountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ThreadCountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   thread.ThreadCountTable,
			Columns: []string{thread.ThreadCountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(threadcount.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.RepostedCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   thread.RepostedTable,
			Columns: []string{thread.RepostedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RepostedIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   thread.RepostedTable,
			Columns: []string{thread.RepostedColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.RepostCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   thread.RepostTable,
			Columns: []string{thread.RepostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RepostIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   thread.RepostTable,
			Columns: []string{thread.RepostColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(thread.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if tuo.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.RemovedImagesIDs(); len(nodes) > 0 && !tuo.mutation.ImagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.ImagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: false,
			Table:   thread.ImagesTable,
			Columns: thread.ImagesPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(media.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Thread{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{thread.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
