// Code generated by ent, DO NOT EDIT.

package thread

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/0xfzz/tuwitt/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldID, id))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldContent, v))
}

// IsCommentDisabled applies equality check predicate on the "is_comment_disabled" field. It's identical to IsCommentDisabledEQ.
func IsCommentDisabled(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldIsCommentDisabled, v))
}

// IsDeleted applies equality check predicate on the "is_deleted" field. It's identical to IsDeletedEQ.
func IsDeleted(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldIsDeleted, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Thread {
	return predicate.Thread(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Thread {
	return predicate.Thread(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Thread {
	return predicate.Thread(sql.FieldContainsFold(FieldContent, v))
}

// IsCommentDisabledEQ applies the EQ predicate on the "is_comment_disabled" field.
func IsCommentDisabledEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldIsCommentDisabled, v))
}

// IsCommentDisabledNEQ applies the NEQ predicate on the "is_comment_disabled" field.
func IsCommentDisabledNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldIsCommentDisabled, v))
}

// VisibilityEQ applies the EQ predicate on the "visibility" field.
func VisibilityEQ(v Visibility) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldVisibility, v))
}

// VisibilityNEQ applies the NEQ predicate on the "visibility" field.
func VisibilityNEQ(v Visibility) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldVisibility, v))
}

// VisibilityIn applies the In predicate on the "visibility" field.
func VisibilityIn(vs ...Visibility) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldVisibility, vs...))
}

// VisibilityNotIn applies the NotIn predicate on the "visibility" field.
func VisibilityNotIn(vs ...Visibility) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldVisibility, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Thread {
	return predicate.Thread(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Thread {
	return predicate.Thread(sql.FieldNotIn(FieldStatus, vs...))
}

// IsDeletedEQ applies the EQ predicate on the "is_deleted" field.
func IsDeletedEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldEQ(FieldIsDeleted, v))
}

// IsDeletedNEQ applies the NEQ predicate on the "is_deleted" field.
func IsDeletedNEQ(v bool) predicate.Thread {
	return predicate.Thread(sql.FieldNEQ(FieldIsDeleted, v))
}

// HasParentThread applies the HasEdge predicate on the "parent_thread" edge.
func HasParentThread() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ParentThreadTable, ParentThreadColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasParentThreadWith applies the HasEdge predicate on the "parent_thread" edge with a given conditions (other predicates).
func HasParentThreadWith(preds ...predicate.Thread) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newParentThreadStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChildThreads applies the HasEdge predicate on the "child_threads" edge.
func HasChildThreads() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChildThreadsTable, ChildThreadsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChildThreadsWith applies the HasEdge predicate on the "child_threads" edge with a given conditions (other predicates).
func HasChildThreadsWith(preds ...predicate.Thread) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newChildThreadsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasImages applies the HasEdge predicate on the "images" edge.
func HasImages() predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, ImagesTable, ImagesPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasImagesWith applies the HasEdge predicate on the "images" edge with a given conditions (other predicates).
func HasImagesWith(preds ...predicate.Media) predicate.Thread {
	return predicate.Thread(func(s *sql.Selector) {
		step := newImagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Thread) predicate.Thread {
	return predicate.Thread(sql.NotPredicates(p))
}
