// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// BlockedUsersRelationship is the predicate function for blockedusersrelationship builders.
type BlockedUsersRelationship func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)

// Thread is the predicate function for thread builders.
type Thread func(*sql.Selector)

// ThreadCount is the predicate function for threadcount builders.
type ThreadCount func(*sql.Selector)

// ThreadLikeUser is the predicate function for threadlikeuser builders.
type ThreadLikeUser func(*sql.Selector)

// UserAccount is the predicate function for useraccount builders.
type UserAccount func(*sql.Selector)

// UserCount is the predicate function for usercount builders.
type UserCount func(*sql.Selector)

// UserFollowerRelationship is the predicate function for userfollowerrelationship builders.
type UserFollowerRelationship func(*sql.Selector)

// UserProfile is the predicate function for userprofile builders.
type UserProfile func(*sql.Selector)
